### ISSUE TITLE
[Bug] App crashes on selecting options with only the app's process detectable

### ISSUE THREAD

**Issue by Atrate** [KeyLo99/PSAUX#1]
```
time: 1579374158393
msg: java.lang.StringIndexOutOfBoundsException: length=0; index=0
stacktrace: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at com.k3.psaux.MainActivity$processLoaderThread.doInBackground(MainActivity.java:263)
	at com.k3.psaux.MainActivity$processLoaderThread.doInBackground(MainActivity.java:246)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
© 2020 deletescape
Created by Anonymous
 View Stats

```
 Info:

Android 9, based on AOSP (Havoc OS)
LG G6
Rooted

**Comment by Atrate** [comment]
It turns out it's not a problem with the flags themselves, just when there's just one process listed (ps) then the flags cause the out of bounds
